#!/bin/bash

# -- dir for all envs
ENV_DIR=/home/${USER}/ENV
mkdir -p $ENV_DIR

# -- current env with link
VENV=${ENV_DIR}/dohl
VLNK=.venv
ln -sf $VENV $VLNK
python3 -m venv $VENV
source $VENV/bin/activate

# -- upgrade pip
python3 -m pip install --upgrade pip

# -- install requirements
pip install -r requirements.txt

# -- install local package
cd .. && pip install .

# -- end text
echo "---"
echo -e "\e[1mto start the environment, type :\e[0m"
echo "source ${VENV}/bin/activate"
echo ""
echo -e "\e[1mto stop the environment, type :\e[0m"
echo "deactivate"
